In [107]:
import numpy as np
from sklearn.datasets import load_digits
digits=load_digits()

In [108]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier


In [109]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(digits.data,digits.target,test_size=0.3)

In [110]:
lr=LogisticRegression(max_iter=10000)
lr.fit(X_train,y_train)
lr.score(X_test,y_test)

0.9592592592592593

In [111]:
svm=SVC()
svm.fit(X_train,y_train)
svm.score(X_test,y_test)

0.9814814814814815

In [112]:
rf=RandomForestClassifier(n_estimators=40)
rf.fit(X_train,y_train)
rf.score(X_test,y_test)

0.9592592592592593

In [113]:
from sklearn.model_selection import KFold
kf=KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [114]:
for train_index, test_index in kf.split([i for i in range(0,9)]):
    print(train_index,test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [115]:
def get_score(model, Xtr,Xtest,ytr,ytest):
    model.fit(Xtr,ytr)
    return model.score(Xtest,ytest)

In [116]:
 print(get_score(LogisticRegression(max_iter=10000),X_train,X_test,y_train,y_test))
# LogisticRegression().get_score(X_test,y_test)

0.9592592592592593


In [117]:
from sklearn.model_selection import StratifiedKFold
folds=StratifiedKFold(n_splits=3)

In [118]:
scores_l=[]
scores_svm=[]
scores_rf=[]

for train_index, test_index in kf.split(digits.data):
    X_train,X_test,y_train,y_test = digits.data[train_index],digits.data[test_index],digits.target[train_index],digits.target[test_index]
    scores_l.append(get_score(LogisticRegression(max_iter=10000),X_train,X_test,y_train,y_test))
    scores_svm.append(get_score(SVC(),X_train,X_test,y_train,y_test))
    scores_rf.append(get_score(RandomForestClassifier(n_estimators=40),X_train,X_test,y_train,y_test))

In [119]:
scores_l

[0.9282136894824707, 0.9415692821368948, 0.9165275459098498]

In [120]:
scores_svm

[0.9666110183639399, 0.9816360601001669, 0.9549248747913188]

In [121]:

scores_rf

[0.9365609348914858, 0.9649415692821369, 0.9131886477462438]

In [122]:
from sklearn.model_selection import cross_val_score


In [127]:

cross_val_score(LogisticRegression(max_iter=10000),digits.data,digits.target)

array([0.92222222, 0.87777778, 0.93871866, 0.93593315, 0.89693593])

In [124]:
%%timeit
cross_val_score(SVC(),digits.data,digits.target)

359 ms ± 7.94 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [125]:
%%timeit
cross_val_score(RandomForestClassifier(n_estimators=40),digits.data,digits.target)

461 ms ± 9.05 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
