In [21]:
import tensorflow as tf
tf.__version__

'2.5.0'

In [22]:
A = tf.constant([[4,3],[6,1]])
A

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[4, 3],
       [6, 1]], dtype=int32)>

In [23]:
V = tf.Variable([[3,1],[5,2]])
V

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[3, 1],
       [5, 2]], dtype=int32)>

In [24]:
B = tf.constant([[5,2],[4,5]])
B

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[5, 2],
       [4, 5]], dtype=int32)>

In [25]:
AB_concat = tf.concat(values=[A,B],axis=1)
AB_concat

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[4, 3, 5, 2],
       [6, 1, 4, 5]], dtype=int32)>

In [26]:
AB_concat1 = tf.concat(values=[A,B],axis=0)
AB_concat1

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[4, 3],
       [6, 1],
       [5, 2],
       [4, 5]], dtype=int32)>

In [27]:
t=tf.zeros(shape=[3,4],dtype=tf.float32)
t

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

In [28]:
t1=tf.ones(shape=[3,4],dtype=tf.float32)
t1

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>

In [29]:
import datetime,warnings,scipy
import pandas as pd 
import numpy as np
import seaborn as sns
import matplotlib as mpl
import matplotlib.pyplot as plt

plt.rcParams["patch.force_edgecolor"]= True
plt.style.use('fivethirtyeight')
mpl.rc('patch',edgecolor='dimgray',linewidth=1)
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "last_expr"
pd.options.display.max_columns=50
%matplotlib inline

warnings.filterwarnings("ignore")


In [30]:
import math
from keras.models import Sequential #has Sequential, Functional and Subclassing
from keras.layers import Dense
from keras.layers import LSTM

from sklearn.preprocessing import MinMaxScaler,StandardScaler
from sklearn.metrics import mean_squared_error

In [34]:
numpy_a = np.arange(1,25,dtype=np.int32)
numpy_a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [70]:
A=tf.constant(numpy_a,shape=(2,3,4))
A,A.ndim

(<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>,
 3)

In [71]:
X=tf.constant([[1,2],
                [3,4],
                [5,6]])

In [72]:
Y=tf.constant([[7,8],
               [9,10],
               [11,12]])

In [73]:
tf.reshape(Y,shape=(2,3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  8,  9],
       [10, 11, 12]], dtype=int32)>

In [74]:
tf.matmul(X,tf.reshape(Y,shape=(2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>